config/routes.rb
Rails.application.routes.draw do

get 'signup', to: 'users#new', as: 'signup'
get 'login', to: 'sessions#new', as: 'login'
get 'logout', to: 'sessions#destroy', as: 'logout'
get '/logout' => 'sessions#destroy'
post '/login' => 'sessions#create'
post '/users' => 'users#create'

  resources :users
  resources :sessions
  root to: 'products#index'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]

  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  resources :orders, only: [:create, :show]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, only: [:index, :new, :create]
  end

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :products
  validates :name, presence: true

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base

  belongs_to :order
  belongs_to :product

  monetize :item_price_cents, numericality: true
  monetize :total_price_cents, numericality: true

end

app/models/order.rb
class Order < ActiveRecord::Base

  belongs_to :user
  has_many :line_items
  has_many :products, through: :line_items

  monetize :total_cents, numericality: true

  validates :stripe_charge_id, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base

  monetize :price_cents, numericality: true
  mount_uploader :image, ProductImageUploader

  belongs_to :category

  validates :name, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
  validates :category, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
has_secure_password

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_filter :authenticate

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to [:admin, :categories], notice: 'Category created!'
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(
      :name
    )
  end

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
before_filter :authenticate
  def show
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
before_filter :authenticate
  def index
    @products = Product.order(id: :desc).all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to [:admin, :products], notice: 'Product created!'
    else
      render :new
    end
  end

  def destroy
    @product = Product.find params[:id]
    @product.destroy
    redirect_to [:admin, :products], notice: 'Product deleted!'
  end

  private

  def product_params
    params.require(:product).permit(
      :name,
      :description,
      :category_id,
      :quantity,
      :image,
      :price
    )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def cart
    @cart ||= cookies[:cart].present? ? JSON.parse(cookies[:cart]) : {}
  end
  helper_method :cart

  def enhanced_cart
    @enhanced_cart ||= Product.where(id: cart.keys).map {|product| { product:product, quantity: cart[product.id.to_s] } }
  end
  helper_method :enhanced_cart

  def cart_subtotal_cents
    enhanced_cart.map {|entry| entry[:product].price_cents * entry[:quantity]}.sum
  end
  helper_method :cart_subtotal_cents


  def update_cart(new_cart)
    cookies[:cart] = {
      value: JSON.generate(new_cart),
      expires: 10.days.from_now
    }
    cookies[:cart]
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['ADMIN_USERNAME'] && password == ENV['ADMIN_PASSWORD']
    end
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
  end

  def add_item
    product_id = params[:product_id].to_s
    modify_cart_delta(product_id, +1)

    redirect_to :back
  end

  def remove_item
    product_id = params[:product_id].to_s
    modify_cart_delta(product_id, -1)

    redirect_to :back
  end

  private

  def modify_cart_delta(product_id, delta)
    cart[product_id] = (cart[product_id] || 0) + delta
    cart.delete(product_id) if cart[product_id] < 1
    update_cart cart
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find(params[:id])
    @products = @category.products.order(created_at: :desc)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
  end

  def create
    charge = perform_stripe_charge
    order  = create_order(charge)

    if order.valid?
      empty_cart!
      redirect_to order, notice: 'Your Order has been placed.'
      OrderMailer.order_confirmation(order).deliver_now
    else
      redirect_to cart_path, flash: { error: order.errors.full_messages.first }
    end

  rescue Stripe::CardError => e
    redirect_to cart_path, flash: { error: e.message }
  end

  private

  def empty_cart!
    # empty hash means no products in cart :)
    update_cart({})
  end

  def perform_stripe_charge
    Stripe::Charge.create(
      source:      params[:stripeToken],
      amount:      cart_subtotal_cents,
      description: "Khurram Virani's Jungle Order",
      currency:    'cad'
    )
  end

  def create_order(stripe_charge)
    order = Order.new(
      email: params[:stripeEmail],
      total_cents: cart_subtotal_cents,
      stripe_charge_id: stripe_charge.id, # returned by stripe
    )

    enhanced_cart.each do |entry|
      product = entry[:product]
      quantity = entry[:quantity]
      order.line_items.new(
        product: product,
        quantity: quantity,
        item_price: product.price,
        total_price: product.price * quantity
      )
    end
    order.save!
    order
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all.order(created_at: :desc)
  end

  def show
    @product = Product.find params[:id]
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
    session[:user_id] = user.id
    redirect_to "/", notice: "logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      redirect_to '/users/new'
  end
end
def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def new
  @user = User.new
end

def create
  @user = User.new(user_params)
  if @user.save
    session[:user_id] = @user.id
    redirect_to "/", notice: "Thank you for signing up!"
  else
    render "new"
  end
end

  private

  def user_params
    params.require(:user).permit( :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/_category.html.erb
<tr>
  <td>
    <h4><%= category.name %></h4>
  </td>
  <td>
    <%= category.created_at %>
  </td>
  <td>
    <%= category.updated_at %>
  </td>
</tr>

app/views/admin/categories/index.html.erb
<section class="admin-catergories-index">

  <header class="page-header">
    <h1>Admin &#xBB; All Categories</h1>
  </header>

  <div class="well">
  <%= link_to '+ New Category', [:new, :admin, :category], class: 'btn btn-info' %>
  </div>

  <div class="panel panel-default catergories">

    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Category</th>
          <th>Date Created</th>
          <th>Updated Date</th>
        </tr>
      </thead>
      <tbody>
        <%= render @categories %>
      </tbody>
    </table>

  </div>

</section>

app/views/admin/categories/new.html.erb
<section class="admin-products-new">
  <header class="page-header">
      <h1>Admin &raquo; New Category</h1>
  </header>

  <div class="well">
    <%= link_to 'All Categories', [:admin, :categories], class: 'btn btn-info' %>
  </div>

  <div class="row">
    <div class="col-sm-6 col-sm-offset-1">
      <%= form_for [:admin, @category] do |form| %>



        <% if form.object.errors.any? %>
          <div class="alert alert-danger">
            <strong>The following errors prevented saving:</strong>
            <ul>
              <% form.object.errors.full_messages.each do |error| %>
                <li><%= error %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, class: 'form-control' %>
        </div>
        <%= form.submit 'Create Category', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</section>

app/views/admin/categories/show.html.erb
<section class="categories-show">

  <header class="page-header">
    <h1>
      <%= @category.name %>
      <small>(<%= pluralize @products.size, 'product' %>)</small>
    </h1>
  </header>

  <div class="products">
    <%= render @products %>
  </div>

</section>

app/views/admin/dashboard/show.html.erb
<h1>Admin::Dashboard#show</h1>
<p>Find me in app/views/admin/dashboard/show.html.erb</p>

app/views/admin/products/_product.html.erb
<tr>
  <td>
    <%= image_tag product.image.tiny %>
  </td>
  <td>
    <h4><%= product.name %></h4>
    <br>
    <p><%= product.description %></p>
  </td>
  <td>
    <%= product.category.name %>
  </td>
  <td>
    <%= product.price %>
  </td>
  <td>
    <%= product.quantity %>
  </td>
  <td>
    <%= link_to fa_icon('trash'), [:admin, product], class: 'btn btn-sm btn-danger', method: :delete, data: { confirm: "Are you sure?" } %>
  </td>
</tr>

app/views/admin/products/index.html.erb
<section class="admin-products-index">

  <header class="page-header">
    <h1>Admin &raquo; All Products</h1>
  </header>

  <div class="well">
    <%= link_to '+ New Product', [:new, :admin, :product], class: 'btn btn-info' %>
  </div>

  <div class="panel panel-default products">

    <table class="table table-bordered">
      <thead>
        <tr>
          <th colspan="2">Product</th>
          <th>Category</th>
          <th>Price</th>
          <th>Qty Remaining</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= render @products %>
      </tbody>
    </table>

  </div>

</section>

app/views/carts/_item.html.erb
<tr>
  <td>
    <%= image_tag product.image.tiny %>
  </td>
  <td>
    <h4><%= product.name %></h4>
    <br>
    <p><%= product.description %></p>
  </td>
  <td>
    <%= product.price %>
  </td>
  <td>
    <%= button_to remove_item_cart_path(product_id: product.id), class: 'btn btn-xs btn-danger' do %> - <% end %>
    <%= quantity %>
    <%= button_to add_item_cart_path(product_id: product.id), class: 'btn btn-xs btn-success' do %> + <% end %>
  </td>
  <td>
    <%= product.price * quantity %>
  </td>
</tr>

app/views/carts/show.html.erb
<section class="cart-show">

  <header class="page-header">
    <h1>My Cart</h1>
  </header>
<% if enhanced_cart.length == 0 %>
  <h1>Your cart is empty!</h1>
  <%= link_to "Back to Home", root_path %>
<% else %>
  <div class="panel panel-default items">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th colspan="2">Product</th>
          <th>Unit Price</th>
          <th>Quantity</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>
        <% enhanced_cart.each do |item| %>
          <%= render 'item', product: item[:product], quantity: item[:quantity].to_i %>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <th colspan="4">
            TOTAL:
          </th>
          <th>
            <%= cart_subtotal_cents / 100.0 %>
          </th>
        </tr>
      </tfoot>
    </table>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <%= form_tag orders_path do %>
        <script
          src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-amount="<%= cart_subtotal_cents %>"
          data-name="Jungle"
          data-description="Khurram Virani's Jungle Order"
          data-locale="auto"
          data-email="kvirani@gmail.com"
          data-currency="cad">
        </script>
      <% end %>
    </div>
  </div>
<% end %>

</section>

app/views/categories/show.html.erb
<section class="categories-show">

  <header class="page-header">
    <h1>
      <%= @category.name %>
      <small>(<%= pluralize @products.size, 'product' %>)</small>
    </h1>
  </header>

  <div class="products">
    <%= render @products %>
  </div>

</section>

app/views/layouts/_top_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Jungle</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'Home', :root %>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            Categories
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <% Category.all.each do |category| %>
              <li><%= link_to category.name, category %></li>
            <% end %>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <div id="user_header" class="dropdown">
      <%= link_to "Sign Up", new_user_path %> or
      <%= link_to "Log In", new_session_path %>
      </div>
       <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">

            <span class="text-danger"><%= fa_icon 'lock', text: 'Admin' %></span>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Dashboard', [:admin, :root] %></li>
            <li><%= link_to 'Products',  [:admin, :products] %></li>
            <li><%= link_to 'Categories',  [:admin, :categories] %></li>
          </ul>
        </li>
        <li>
          <%= link_to cart_path do %>
            <%= fa_icon "shopping-cart" %> My Cart (<%= cart.size %>)
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jungle</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
  Signed in as <%= current_user.email %> | <%= link_to "Logout", '/logout' %>
<% end %>
  <%= render 'layouts/top_nav' %>

  <main class="container">
    <%= yield %>
  </main>

  <%= yield :end_of_body %>
</body>
</html>

app/views/orders/_item.html.erb
<tr>
  <td>
    <%= image_tag product.image.tiny %>
  </td>
  <td>
    <h4><%= product.name %></h4>
    <br>
    <h6><%= product.description %></h6>
  </td>
  <td>
    <%= product.price %>
  </td>
  <td>
    <%= line_item.quantity %>
  </td>
  <td>
    <%= product.price * line_item.quantity %>
  </td>
</tr>

app/views/orders/show.html.erb
   <h1>Order <%= @order.id %></h1>
  </header>

  <div class="order-summary jumbotron">
    <h4>Thank you for your order!</h4>
    <h5><%= @order.email%></h5>

    <div class="panel panel-default items">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th colspan="2">Product</th>
          <th>Unit Price</th>
          <th>Quantity</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>
        <% @order.line_items.each do |line_item| %>
          <%= render 'item', line_item: line_item, product: line_item.product %>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <th colspan="4">
            TOTAL:
          </th>
          <th>
            <%= @order.total_cents / 100.0 %>
          </th>
        </tr>
      </tfoot>
    </table>
  </div>


  </div>

  <%= link_to "Continue Shopping", root_path, class: 'btn btn-lg btn-primary' %>
</section>

app/views/products/_product.html.erb
<article class="product">
  <header>
    <%= link_to product do %>
      <%= image_tag product.image.thumb, alt: product.name %>
      <h4><%= product.name %></h4>
    <% end %>
  </header>
  <p class="description">
    <%= product.description %>
  </p>
  <footer class="actions">
    <%= button_to add_item_cart_path(product_id: product.id), class: 'btn btn-primary' , method: :post do %>
      <%= fa_icon "shopping-cart", text: 'Add' %>
    <% end %>
    <%= link_to product, class: 'btn btn-default pull-right' do %>
      Details &raquo;
    <% end %>
  </footer>

  <aside class="price">
    <%= humanized_money_with_symbol product.price %>
  </aside>
  <% unless product.quantity != 0 %>
  <aside class="soldout">
    SOLD OUT!!
  </aside>
  <% end %>
</article>

app/views/products/index.html.erb
<section class="products-index">

  <header class="page-header">
    <h1>Products</h1>
  </header>

  <div class="products">
    <%= render @products %>
  </div>

</section>

app/views/products/show.html.erb
<section class="products-show">

  <header class="page-header">
    <h1><%= link_to @product.category.name, @product.category %> &raquo; <%= @product.name %></h1>
  </header>

  <article class="product-detail">

    <div class="row">

      <div class="col-sm-4">
        <%= image_tag @product.image.url, class: 'main-img' %>
      </div>

      <div class="col-sm-8">
        <dl class="dl-horizontal">
          <dt>Name</dt>
          <dd><%= @product.name %></dd>
          <dt>Description</dt>
          <dd><%= @product.description %></dd>
          <dt>Quantity</dt>
          <dd><%= @product.quantity %></dd>
          <dt>Price</dt>
          <dd><%= @product.price %></dd>
        </dl>
      </div>
    </div>

  </article>

</section>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |form| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %><br />
    <%= form.text_field :email %>
  </div>
  <div class="field">
    <%= form.label :password %><br />
    <%= form.password_field :password %>
  </div>
  <div class="field">
    <%= form.label :password_confirmation %><br />
    <%= form.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= form.submit "Sign Up" %></div>
<% end %>